### ISSUE TITLE
Wrong include in PieElement.h

### ISSUE THREAD

**Issue by werner-freytag** [AlexandrGraschenkov/MagicPie#12]
In PieElement.h you include Foundation.h while UIColor is used, which is part of UIKit.h . This can product problems when using MagicPie with Swift.

Can you replace
#import <Foundation/Foundation.h>

with
#import <UIKit/UIKit.h>

Thanks!

**Comment by AlexandrGraschenkov** [comment]
Hi. 
Sorry for too late response, seams I missed this issue in notifications. I added `#import <UIKit/UIKit.h>` in last version.
