### ISSUE TITLE
demo photos in README are broken.

### ISSUE THREAD

**Issue by crobertsbmw** [AlexandrGraschenkov/MagicPie#17]
The first few photos in the README won't load.

**Comment by AlexandrGraschenkov** [comment]
In my browser all looks fine. Check can you see this gif https://github.com/Sk0rpion/MagicPie/blob/master/MagicPie.gif?raw=true. If no, please check this gif url https://raw.githubusercontent.com/AlexandrGraschenkov/MagicPie/master/MagicPie.gif.

**Comment by crobertsbmw** [comment]
I think it was github's problem. After I posted the issue, none of them were working for me. Now they are all working again.
