### ISSUE TITLE
Problems starting angle of a pie chart

### ISSUE THREAD

**Issue by duxinfeng** [AlexandrGraschenkov/MagicPie#18]
Hi，

`PieLayer *pieLayer = [[PieLayer alloc] init];
    pieLayer.frame = CGRectMake(100, 100, 200, 200);
    pieLayer.maxRadius = 60;
    pieLayer.minRadius = 30;
    pieLayer.startAngle = 0;
    pieLayer.endAngle = 360;
    pieLayer.showTitles = ShowTitlesNever;
    
    PieElement *elem1 = [PieElement pieElementWithValue:1 color:[self randomColor]];
    PieElement *elem2 = [PieElement pieElementWithValue:3 color:[self randomColor]];
    
    [pieLayer addValues:@[elem1] animated:NO];
    [pieLayer addValues:@[elem2] animated:NO];

    [self.view.layer addSublayer:pieLayer];`

This is not a problem！

![qq20151021-0](https://cloud.githubusercontent.com/assets/8338102/10630113/1aa5154c-7807-11e5-9ffd-0e3e13f48163.png)

But, Starting angle is not starting from   pieLayer.startAngle = 0;  ,
` PieElement *elem1 = [PieElement pieElementWithValue:3 color:[self randomColor]];`

![qq20151021-1](https://cloud.githubusercontent.com/assets/8338102/10630123/291dbc6e-7807-11e5-9fa6-ae01b32b9039.png)

What should I do？
Thanks！

**Comment by AlexandrGraschenkov** [comment]
:smile: Try `2` value and `4` value. 

For your behavior you can set 
``` Objective-C
    pieLayer.startAngle = 90;
    pieLayer.endAngle = -270;
```

**Comment by duxinfeng** [comment]
:grin:  Thanks!

If the value is not a constant，what should I do？

 3 value and 4 value
 5 value and 4 value.
 7 value and 4 value.
...

**Comment by AlexandrGraschenkov** [comment]
Look examples. There example code where you can change value with\without animation.
