### ISSUE TITLE
Upload Privacy Policy

### ISSUE THREAD

**Issue by sumit-vts** [AlexandrGraschenkov/MagicPie#21]
Apple says "Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect."

Please add privacy policy

**Comment by AlexandrGraschenkov** [comment]
@sumit-vts also make minor changes with header name:
`MagicPieLayer.h` renamed to `MagicPie.h`
